spring:
  application:
    name: freyr
  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
server.port: 8082

management.endpoint.health.enabled: true

