
management:
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  application:
    name: freya
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/freya_db
    username: admin
    password: password