app:
  kafka:
    order-topic: orders
    user-topic: users

management:
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  application:
    name: freya
  kafka:
    bootstrap-servers:
      - localhost:29092
      - localhost:39092
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/freya_db
    username: admin
    password: password

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    groups-order: asc