name: Shared Push
on:
  workflow_call:
    inputs:
      compose-file-path:
        required: true
        type: string
jobs:
  shared-steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run Docker Compose file
        run: docker compose -f ${{ inputs.compose-file-path }} up --build -d
        env:
          GRADLE_USER_HOME: ${{ env.HOME }}/.gradle

      - name: Upload build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/